osj-project/osj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from osj import views as core_views
from osj.forms import UserLoginForm, UserPasswordResetForm, UserPasswordChangeForm
import notifications.urls
from django_email_verification import urls as email_urls  # include the urls

urlpatterns = [
    path('', include('pages.urls'), name='index'),
    path('jewelry/', include('things.urls')),
    path('user/', include('profiles.urls')),
    path('articles/', include('articles.urls')),
    path('reports/', include('reports.urls'), name='reports'),
    path('admin/', admin.site.urls),
    path(
        'auth/login/',
        auth_views.LoginView.as_view(
            template_name="registration/login.html",
            authentication_form=UserLoginForm
            ),
        name='login'
        ),
    path(
        'auth/password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            form_class=UserPasswordResetForm
            ),
        ),
    path(
        'auth/password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change_form.html",
            form_class=UserPasswordChangeForm
            ),
        ),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/register', core_views.registration, name='registration'),
    path('auth/whatsnext', core_views.afterRegistration, name='afterRegistration'),
    path('tinymce/', include('tinymce.urls'), name='tinymce'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('tz_detect/', include('tz_detect.urls')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('email/', include(email_urls)),  # connect them to an arbitrary path
    path('newVerificationLink/', core_views.newVerificationLink, name='newVerificationLink'),
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls'))
]

osj-project/profiles/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('<str:slug>/', views.ProfileDetailView.as_view(), name='profile'),
    path('<str:slug>/edit/', login_required(views.profileUpdateView), name='profileUpdate'),
] 

osj-project/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_bleach.models import BleachField
from notifications.signals import notify
from django_email_verification import send_email
from django.contrib.contenttypes.fields import GenericRelation
from reports.models import Report

# Based on solution at https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html

class Profile(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    description = BleachField(max_length=1000, blank=True)
    image = models.ImageField(upload_to='profile_photos', blank=True)
    email_verified = models.BooleanField(default=False)
    reports = GenericRelation(Report)


def sendVerificationEmail():
    pass


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance, slug=instance.username)
        # Send welcome notification
        notificationSender = User.objects.get(username="adam")
        recipient = instance
        verb = "Welcome to OpenJewelry!"
        description = "Thank you for joining the OpenJewelry commnuity! We're glad to have you here."
        notify.send(sender=notificationSender, recipient=recipient, verb=verb, description=description)
        # Send verification email
        profile.email_verified = False
        profile.save()
        send_email(instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

osj-project/profiles/forms.py
from cProfile import Profile
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from tinymce.widgets import TinyMCE
#import taggit
from django_bleach.forms import BleachField
from PIL import Image as pImage # Image conflicts with the model of the same name
from django.conf import settings


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class ProfilePhotoForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput())
    imageX = forms.FloatField(widget=forms.HiddenInput())
    imageY = forms.FloatField(widget=forms.HiddenInput())
    imageWidth = forms.FloatField(widget=forms.HiddenInput())
    imageHeight = forms.FloatField(widget=forms.HiddenInput())
    class Meta:
        model = Profile
        fields = ['image', 'imageX', 'imageY', 'imageWidth', 'imageHeight']

    def save(self):
        profile = super(ProfilePhotoForm, self).save()
        x = self.cleaned_data.get('imageX')
        y = self.cleaned_data.get('imageY')
        w = self.cleaned_data.get('imageWidth')
        h = self.cleaned_data.get('imageHeight')
        image = pImage.open(profile.image)
        croppedImage = image.crop((x, y, x+w, y+h))
        resizedImage = croppedImage.resize((settings.PROFILE_PHOTO_SIZE), pImage.ANTIALIAS)
        resizedImage.save(profile.image.path)
        return profile
    

class ProfileDataForm(forms.ModelForm):
    description = BleachField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 80, 'rows': 20}
        )
    )
    class Meta:
        model = Profile
        fields = ['description']


class UserDataForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

osj-project/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import  HttpResponseForbidden
from django.views.generic import DetailView
from taggit.models import Tag
import things
import profiles
from .forms import ProfilePhotoForm, ProfileDataForm, UserDataForm
from osj.views import getUserContext
from things.views import getJewelryContext

class ProfileDetailView(DetailView):
    model = profiles.models.Profile
    template_name = 'profiles/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        jewelry = self.object.user.thing_set.all()
        context.update({'pieces': getJewelryContext(jewelry)})
        if self.request.user.is_authenticated:
            context.update(getUserContext(self.request))
            if self.request.user == self.object.user:
                likedPieces = things.models.Thing.objects.filter(likes=self.request.user)
                liked = getJewelryContext(likedPieces)
                context.update({
                    'editable': True,
                    'liked': liked
                    })
        return context


def profileUpdateView(request, slug):
    #https://stackoverflow.com/questions/54404250/django-populate-form-using-function-based-view-with-multiple-forms
    profile = get_object_or_404(profiles.models.Profile, slug=slug)
    if request.method == 'POST':
        photo_form = ProfilePhotoForm(request.POST, request.FILES, instance=profile)
        user_data_form = UserDataForm(request.POST, instance=profile.user)
        profile_data_form = ProfileDataForm(request.POST, instance=profile)
        valid = False
        if photo_form.is_valid():
            valid = True
            photo_form.save()
        if profile_data_form.is_valid():
            valid = True
            currentEmail = profile.user.email
            newEmail = user_data_form.data['email']
            if currentEmail != newEmail:
                # The email has changed
                profile.email_verified = False
            profile_data_form.save()
        if user_data_form.is_valid():
            valid = True
            user_data_form.save()
    else:
        photo_form = ProfilePhotoForm(instance=profile)
        profile_data_form = ProfileDataForm(instance=profile)
        user_data_form = UserDataForm(instance=profile.user)
    
    context = {
        'photo_form': photo_form,
        'profile_data_form': profile_data_form,
        'user_data_form': user_data_form
    }
    if request.user.is_authenticated:
        # they had better be authenticated
        context.update(getUserContext(request))

    if profile.user != request.user:
        return HttpResponseForbidden(u"Can't touch this.")
    if (request.method == 'POST' and valid):
        return redirect('profileUpdate', slug=slug)
    else:
        return render(request, 'profiles/editProfile.html', context)

osj-project/profiles/templates/profiles/editProfile.html
{% extends 'pages/base.html' %}
{% load static %}

{% block scripts %}
    <title>OpenJewelry: Edit Profile</title>
    <link href="{% static 'pages/cropper/cropper.css' %}" rel="stylesheet">
    <script src="{% static "pages/cropper/cropper.js" %}"></script>
    <script src="{% static 'pages/cropper/jquery-cropper.js' %}"></script>
    <script>
        // Cropping adapted from https://simpleisbetterthancomplex.com/tutorial/2017/03/02/how-to-crop-images-in-a-django-application.html
        $(function () {
            var $uploaded_image = $("#uploaded_image");
            var cropBoxData;
            var canvasData;
            $("#id_image").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#uploaded_image").attr("src", e.target.result);
                        $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });

            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $uploaded_image = $("#uploaded_image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function () {
                $uploaded_image.cropper({
                    //viewMode: 1,
                    aspectRatio: 1,
                    minCropBoxWidth: 10,
                    ready: function () {
                        $uploaded_image.cropper("setCanvasData", canvasData);
                        $uploaded_image.cropper("setCropBoxData", cropBoxData);
                    }
                });
            }).on("hidden.bs.modal", function () {
            cropBoxData = $uploaded_image.cropper("getCropBoxData");
            canvasData = $uploaded_image.cropper("getCanvasData");
            $uploaded_image.cropper("destroy");
            });

            // Enable zoom in button
            $(".js-zoom-in").click(function () {
                $uploaded_image.cropper("zoom", 0.1);
            });

            // Enable zoom out button
            $(".js-zoom-out").click(function () {
                $uploaded_image.cropper("zoom", -0.1);
            });

            // Collect data and post to server
            $(".js-crop-and-upload").click(function () {
                var cropData = $uploaded_image.cropper("getData");
                $("#id_imageX").val(cropData["x"]);
                $("#id_imageY").val(cropData["y"]);
                $("#id_imageHeight").val(cropData["height"]);
                $("#id_imageWidth").val(cropData["width"]);
                $("#photo_form").submit();
                //$("#data_form").submit();
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container mt-3">
        {{ photo_form.media }}
        <form method="POST" enctype='multipart/form-data' id="photo_form" class="message-form m-4">{% csrf_token %}
            <div class="row m-2">
                <div class="col-md-4">
                    {% if photo_form.instance.image %}
                        <img class="profile-photo" src="/media/{{ photo_form.instance.image }}"></img>
                    {% else %}
                        <img src="/media/profile_photos/default.png" class="profile-photo" alt="profile photo">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h3>Profile Photo</h3>
                    <p>Say cheese!</p>
                    {{ photo_form.image }}
                    {{ photo_form.imageX }}
                    {{ photo_form.imageY }}
                    {{ photo_form.imageWidth }}
                    {{ photo_form.imageHeight }}
                    {% for error in photo_form.image.errors %}
                        <strong>{{ error|escape }}</strong>
                    {% endfor %}
                </div>
            </div>
        </form>

        <hr/>

        <form method="POST" enctype='multipart/form-data' class="message-form m-4">{% csrf_token %} <!--id="data_form"-->
            {{ profile_data_form.media }}
            {{ user_data_form.media }}
            <div class="row">
                <div class="col-md-4">
                    <label for="id_first_name" class="form-label">First Name</label>
                    {{ user_data_form.first_name }}
                </div>
                <div class="col-md-4">
                    <label for="id_last_name" class="form-label">Last Name</label>
                    {{ user_data_form.last_name }}
                </div>
                <div class="col-md-4">
                    <label for="id_email" class="form-label">Email</label>
                    {{ user_data_form.email }}
                    <div id="emailHelp" class="form-text">If you change your email, you will need to verify the new address before using your account again.</div>
                </div>
            </div>

            <hr/>

            <div class="row">
                <div class="">
                    <h3>Description</h3>
                    <p>Tell us a bit about yourself</p>
                </div>
                {{ profile_data_form.description }}
                {% for error in profile_data_form.description.errors %}
                    <strong>{{ error|escape }}</strong>
                {% endfor %}
            </div>
            <button type="submit" class="save btn btn-primary m-2">Save</button>
            <a class="btn btn-warning" href="/auth/password_change">Change Password</a>
        </form>
    </div>

    <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
                <div class="img-container">
                    <img src="" id="uploaded_image" class="profile-photo" style="//max-width: 100%;">
                </div>
            </div>
            <div class="modal-footer">
            <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                <span class="glyphicon glyphicon-zoom-in"></span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                <span class="glyphicon glyphicon-zoom-out"></span>
                </button>
            </div>
            <button type="button" class="btn btn-default" data-bs-dismiss="modal">Nevermind</button>
            <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

osj-project/profiles/templates/profiles/profile.html
{% extends 'pages/base.html' %}

{% block scripts %}
    <title>OpenJewelry: {{ profile.user.username }}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">
    </script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>

    <meta property="og:url" content="https://{{ request.get_host }}{{ request.get_full_path }}" />
    <meta property="og:title" content="OpenJewelry: {{ profile.user.username }}" />
    <meta property="og:description" content="{{ page.content | slice:'0:100'}}" />
    <meta property="og:type" content="website" />
    {% if profile.image %}
        <meta property="og:image" content="https://{{ request.get_host }}{{ profile.image.url }}" />
        <meta name="twitter:image" content="https://{{ request.get_host }}{{ profile.image.url }}">
    {% else %}
        <meta property="og:image" content="https://{{ request.get_host }}/media/profile_photos/default.png" />
        <meta name="twitter:image" content="https://{{ request.get_host }}/media/profile_photos/default.png">
    {% endif %}

    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="{{ request.get_host }}">
    <meta property="twitter:url" content="https://{{ request.get_host }}{{ request.get_full_path }}">
    <meta name="twitter:title" content="OpenJewelry: {{ profile.user.username }}">
    <meta name="twitter:description" content="The Internet's home for wearable art of all kinds">
{% endblock %}


{% block content %}
    <div class="jumbotron d-flex min-vh-100">
        <div class="container mt-3">
            <div>
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h1>{{ profile.user.username }}</h1>
                    </div>
                    <div class="col-auto">
                        <div class="row">
                            <h6 class="jewelry-header-subtitle">{{ profile.user.first_name }} {{ profile.user.last_name }}</h6>
                            <h6 class="jewelry-header-subtitle">Member Since {{ profile.user.date_joined }}</h6>
                        </div>
                    </div>
                    <div class="col-auto edit-button-col">
                        {% if editable %}
                            <a href="/user/{{ profile.slug }}/edit" style="font-size: 2rem;" class="bi-pencil-square"></a>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {% if profile.image %}
                            <img src="{{ profile.image.url }}" class="profile-photo" alt="profile photo">
                        {% else %}
                            <img src="/media/profile_photos/default.png" class="profile-photo" alt="profile photo">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        {{ profile.description|safe }}
                    </div>
                </div>
                <hr/>

                <div class="row">
                    <div class="col-md-12">
                        <h3>Jewelry created by {{ profile.user.username }}:</h3>
                        {% include "things/jewelry-grid-block.html" with pieces=pieces %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        {% if editable %}
                            <hr/>
                            <h3>My Likes:</h3>
                            {% include "things/jewelry-grid-block.html" with pieces=liked %}
                        {% endif %}
                    </div>

                </div>

                <div class="row">
                    <p><a href="/reports/new/profile/{{ profile.id }}">Report this content</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}